mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('submitsys/', include('submitsys.urls')),
    path('', include('submitsys.urls')),
]

mysite/polls/urls.py
from django.urls import path
from . import views


app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/submitsys/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('courses', views.course_console, name='course_console'),
    path('courses/create', views.course_create, name='course_create'),
    path('courses/<int:course_id>/enroll', views.new_enrollment, name='new_enrollment'),
    path('courses/<int:course_id>/enrollSingle', views.single_enrollment, name='add_single_enrollment'),
    path('courses/<int:course_id>/enrollSingle/submit', views.save_single_enrollment, name='save_single_enrollment'),
    path('courses/<int:course_id>/enroll/status', views.course_enrollment, name='course_enrollment'),
    path('courses/<int:course_id>/assignments', views.assignment_console, name='assignment_console'),
    path('courses/<int:course_id>/assignments/redirect', views.assignment_create, name='assignment_create'),
    path('courses/<int:course_id>/assignments/create', views.assignment_form, name='assignment_form'),
    path('<int:assignment_id>/', views.detail, name='detail'),
    path('student', views.student_intro, name='student_intro'),
    path('student/login', views.student_login, name='student_login'),
    path('student/<int:student_id>/', views.student_console, name='student_console'),
    path('student/<int:student_id>/course/<int:course_id>/assignments', views.student_assignments, name='student_assignments'),
    path('student/<int:student_id>/course/<int:course_id>/assignments/<int:assignment_id>/submissions',
         views.submission_edit,
         name='submission_edit'),
    path('student/<int:student_id>/course/<int:course_id>/assignments/<int:assignment_id>/submissions/<int:submission_id>/save',
         views.submission_file_save,
         name='submission_file_save'),
    path('student/<int:student_id>/course/<int:course_id>/assignments/<int:assignment_id>/submissions/<int:submission_id>/create',
         views.submission_file_create,
         name='submission_file_create'),

]

mysite/submitsys/models.py
from django.db import models
import datetime


# Create your models here.
class Course(models.Model):
    course_name = models.CharField(max_length=8, default='Course Name')

    def __str__(self):
        return self.course_name


class Assignment(models.Model):
    assignment_name = models.CharField(max_length=15, default='HW0')
    course_fk = models.ForeignKey(Course, on_delete=models.CASCADE)
    point_value = models.IntegerField()
    due_date = models.DateTimeField(default=datetime.datetime.now() + datetime.timedelta(weeks=2))

    def __str__(self):
        return self.assignment_name


class Rubric(models.Model):
    assignment_fk = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    is_blank = models.BooleanField(default=True)


class RubricSection(models.Model):
    rubric_fk = models.ForeignKey(Rubric, on_delete=models.CASCADE)
    name = models.CharField(max_length=1000, default="General")


class RubricItem(models.Model):
    section_fk = models.ForeignKey(RubricSection, on_delete=models.CASCADE)
    text = models.CharField(max_length=1000, default="")
    possible_points = models.IntegerField()
    is_optional = models.BooleanField()


class Student(models.Model):
    student_fname = models.TextField(default='NULL')
    student_lname = models.TextField(default='NULL')
    student_num = models.CharField(max_length=7, default='NULL')
    student_email = models.CharField(max_length=30)
    student_courses = models.ManyToManyField(Course)

    def __str__(self):
        return self.student_fname + " " + self.student_lname


class Submission(models.Model):
    student_fk = models.ForeignKey(Student, on_delete=models.CASCADE)
    assignment_fk = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    mongo_db = models.CharField(max_length=512, default="NULL")


class SubmissionFile(models.Model):
    file_name = models.CharField(max_length=80, default="NULL")
    file_contents = models.TextField(default="NULL")
    submission_fk = models.ForeignKey(Submission, on_delete=models.CASCADE)

    def __str__(self):
        return self.file_name

mysite/submitsys/views.py
import csv

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.urls import reverse
from datetime import datetime, timezone

from .models import Assignment, Course, Student, Submission, SubmissionFile


def index(request):
    template = loader.get_template("submitsys/index.html")
    return HttpResponse(template.render({}, request))


def course_console(request):

    courses = Course.objects.all()
    assignments = []

    for course in courses:
        course_assignments = Assignment.objects.filter(course_fk=course.id)
        for assignment in course_assignments:
            if assignment.due_date > datetime.now(timezone.utc):
                assignments.append(assignment)

    context = {
        "courses": courses,
        "assignments": assignments,
    }
    template = loader.get_template('submitsys/course_dashboard.html')
    return HttpResponse(template.render(context, request))


def course_create(request):
    course = Course.objects.create(course_name=request.POST['courseName'])
    course.save()
    return HttpResponseRedirect(reverse('course_console'))


def assignment_console(request, course_id): # TODO: Link to a new view with all submissions
    course: Course = get_object_or_404(Course, pk=course_id)

    context = {
        "assignments": Assignment.objects.filter(course_fk=course_id),
        "course_id": course_id,
    }
    template = loader.get_template('submitsys/assignment.html')
    return HttpResponse(template.render(context, request))


def assignment_create(request, course_id):
    assignment = Assignment.objects.create(assignment_name=request.POST['assignmentTitle'],
                                           course_fk=Course.objects.get(pk=course_id),
                                           point_value=0)
    assignment.save()
    return HttpResponseRedirect(reverse('assignment_console', args=(course_id,)))


def assignment_form(request, course_id):  # Will be a form to input assignment name, pt vals, upload rubric
    context = {
        "course_id": course_id,
    }
    template = loader.get_template('submitsys/assignment_form.html')
    return HttpResponse(template.render(context, request))


def detail(request, assignment_id):
    return HttpResponse("You're looking at assignment %s." % assignment_id)


def student_intro(request):
    template = loader.get_template('submitsys/studentintro.html')
    return HttpResponse(template.render({}, request))


def student_login(request):
    return HttpResponseRedirect(reverse('student_console', args=(request.GET['student_id'],)))


def student_console(request, student_id):
    student = Student.objects.get(pk=student_id)
    courses = student.student_courses.all()
    assignments = []

    for course in courses:
        course_assignments = Assignment.objects.filter(course_fk=course.id)
        for assignment in course_assignments:
            if assignment.due_date > datetime.now(timezone.utc):
                assignments.append(assignment)

    context = {
        'student': student,
        'courses': courses,
        'assignments': assignments
    }
    template = loader.get_template('submitsys/student_console.html')
    return HttpResponse(template.render(context, request))


def student_assignments(request, student_id, course_id):
    context = {
        'student': Student.objects.get(pk=student_id),
        'course': Course.objects.get(pk=course_id),
        'assignments': Assignment.objects.filter(course_fk=course_id)
    }
    template = loader.get_template('submitsys/student_assignments.html')
    return HttpResponse(template.render(context, request))


def submission_edit(request, student_id, course_id, assignment_id):
    student = Student.objects.get(pk=student_id)
    assignment = Assignment.objects.get(pk=assignment_id)

    try:
        submission = Submission.objects.get(student_fk=student_id, assignment_fk=assignment_id)
    except Submission.DoesNotExist:
        submission = Submission.objects.create(student_fk=student, assignment_fk=assignment)

    files = SubmissionFile.objects.filter(submission_fk=submission.id)

    context = {
        'student': student,
        'course': Course.objects.get(pk=course_id),
        'assignment': assignment,
        'submission': submission,
        'files': files
    }

    template = loader.get_template('submitsys/submission_edit.html')
    return HttpResponse(template.render(context, request))


def submission_file_save(request, student_id, course_id, assignment_id, submission_id):
    submission = Submission.objects.get(pk=submission_id)
    file = SubmissionFile.objects.filter(submission_fk=submission_id)
    student = Student.objects.get(pk=student_id)

    if submission.student_fk == student:

        if len(file) == 0:
            file = SubmissionFile.objects.create(submission_fk=submission, file_name='', file_contents='')
        else:
            file = file[0]

        file.file_name = request.POST['filename']
        file.file_contents = request.POST['filebody']
        file.save()

    return HttpResponseRedirect(reverse('submission_edit', args=[student_id, course_id, assignment_id]))


def submission_file_create(request, student_id, course_id, assignment_id, submission_id):
    submission = Submission.objects.get(pk=submission_id)
    file = SubmissionFile(submission_fk=submission)

    with open(request.POST['fileUpload']) as f:
        file.file_contents = f.read()
        file.file_name = request.POST['fileUpload']

    file.save()
    return HttpResponseRedirect(reverse('submission_edit', args=[student_id, course_id, assignment_id]))


def new_enrollment(request, course_id):

    context = {
        'course': Course.objects.get(pk=course_id)
    }
    template = loader.get_template('submitsys/new_enrollment.html')
    return HttpResponse(template.render(context, request))


def course_enrollment(request, course_id):
    with open(request.POST['student_upload']) as file:
        reader = csv.reader(file)
        for row in reader:
            student, created = Student.objects.get_or_create(
                student_num=row[0],
                student_email=row[1]
            )
            student.save()
            student.student_courses.add(Course.objects.get(pk=course_id))
    return HttpResponseRedirect(reverse("new_enrollment", args=[course_id]))


def single_enrollment(request, course_id):
    course: Course = get_object_or_404(Course, pk=course_id)
    return render(request, 'submitsys/add_single.html', context={'course': course})

def save_single_enrollment(request, course_id):
    course: Course = get_object_or_404(Course, pk=course_id)
    student: Student
    student, created = Student.objects.get_or_create(student_email=request.POST['email'])
    student.student_fname = request.POST['firstname']
    student.student_lname = request.POST['lastname']
    student.student_courses.add(course)
    student.save()
    return HttpResponseRedirect(reverse('assignment_console', args=[course_id]))

mysite/submitsys/templates/submitsys/add_single.html
{% extends "submitsys\\dashboard.html" %}

{% block content %}

    <form class="col-12" action="{% url 'save_single_enrollment' course.id %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="email">Email address</label>
            <input type="email" class="form-control" id="email" aria-describedby="emailHelp"
                   placeholder="Enter student email" name="email">
            <small id="emailHelp" class="form-text text-muted">We only accept umbc.edu email addresses.</small>
        </div>
        <div class="form-group">
            <label>Name</label>
            <div class="form-row">

                <div class="col">
                    <input class="form-control" type="text" id="firstname" name="firstname" placeholder="First name">
                </div>
                <div class="col">
                    <input class="form-control" type="text" id="lastname" name="lastname" placeholder="Last name">
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

{% endblock %}

mysite/submitsys/templates/submitsys/assignment.html
{% extends "submitsys\\dashboard.html" %}

{% block content %}

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <div class="container">
            <div class="card-deck mb-3 text-center">
                {% for assignment in assignments %}
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal">{{ assignment.assignment_name }}</h4>
                        </div>

                        <div class="card-body">
                            <h1 class="card-title pricing-card-title"><small class="text-muted">Go to assignment
                                submissions</small></h1>


                            <form action="#" method="get">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-lg btn-block btn-primary">Go!</button>
                            </form>
                        </div>
                    </div>
                {% endfor %}

                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Create New Assignment</h4>
                    </div>

                    <div class="card-body">
                        <h3 class="card-title pricing-card-title"><small class="text-muted">
                            Create a new assignment
                        </small></h3>


                        <form action="{% url 'assignment_create' course_id %}" method="post">
                            {% csrf_token %}

                            <input type="text" class="form-control" placeholder="Enter new assignment name..." value=""
                                   name="assignmentTitle"/>
                            <br/>
                            <button type="submit" class="btn btn-lg btn-block btn-primary">Go!</button>
                        </form>
                    </div>
                </div>

                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Enroll New Students</h4>
                    </div>

                    <div class="card-body">
                        <a href="{% url 'new_enrollment' course_id %}">
                            <svg class="bi bi-plus-circle-fill" width="20px" height="20px" viewBox="0 0 16 16"
                                 fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd"
                                      d="M16 8A8 8 0 110 8a8 8 0 0116 0zM8.5 4a.5.5 0 00-1 0v3.5H4a.5.5 0 000 1h3.5V12a.5.5 0 001 0V8.5H12a.5.5 0 000-1H8.5V4z"
                                      clip-rule="evenodd"/>
                            </svg>
                            Upload CSV
                        </a>
                        <hr/>
                        <a href="{% url 'add_single_enrollment' course_id %}">
                            <svg class="bi bi-plus-circle-fill" width="20px" height="20px" viewBox="0 0 16 16"
                                 fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd"
                                      d="M16 8A8 8 0 110 8a8 8 0 0116 0zM8.5 4a.5.5 0 00-1 0v3.5H4a.5.5 0 000 1h3.5V12a.5.5 0 001 0V8.5H12a.5.5 0 000-1H8.5V4z"
                                      clip-rule="evenodd"/>
                            </svg>
                            Add single student
                        </a>

                    </div>
                </div>

            </div>
        </div>
    </div>

{% endblock %}

mysite/submitsys/templates/submitsys/assignment_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>The assignment creation form</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>
<form action="{% url 'assignment_create' course_id %}" method="post">
    {% csrf_token %}
    <div class="container">
    <div class=form-group">
        <label for="assignmentTitle">Assignment Title</label>
        <input type="text" class="form-control" id="assignmentTitle" name="assignmentTitle" placeholder="Enter new assigment title">
    </div>
    <div>
        <label for="assignmentPointVal">Assignment Point Value</label>
        <input type="text" class="form-control" id="assignmentPointVal" placeholder="Enter assignment point value">
    </div>
    <div class="form-group">
        <label for="rubricUpload">Upload Rubric CSV</label>
        <input type="file" class="form-control-file" id="rubricUpload">
    </div>
    <div class="form-group">
        <label for="requiredFiles">Enter required file names</label>
        <textarea class="form-control" id="requiredFiles" rows="3"></textarea>
    </div>
    <button class="btn btn-primary" type="submit">Submit</button>
    </div>
</form>
</body>
</html>

mysite/submitsys/templates/submitsys/course.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>The course console</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<div class="container">
    The following courses are registered in the system:
    <div class="list-group">
        {% for course in courses %}
        <a href="{% url 'assignment_console' course.id %}" class="list-group-item list-group-item-action">{{course.course_name}}</a>
        {% endfor %}
    </div>
</div>
<div class="container">
<hr/>
    <form action="{% url 'course_create' %}" method="post">
        <div class="form-group">
            {% csrf_token %}
            <input type="textarea" class='form-control' name="courseName" placeholder="Enter new course name" value=""/>
            <button type="button" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>
</body>
</html>

mysite/submitsys/templates/submitsys/course_dashboard.html
{% extends "submitsys/dashboard.html" %}

{% block content %}


    <div class="container">
        <div class="card-deck mb-3 text-center">
            {% for course in courses %}
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ course.course_name }}</h4>
                    </div>

                    <div class="card-body">
                        {%  if course.assignment_set.all %}
                        <h3 class="card-title pricing-card-title"><small class="text-muted">Upcoming
                            Assignments:</small></h3>
                        <ul class="list-unstyled mt-3 mb-4">
                            {% for assignment in course.assignment_set.all %}
                                <li>{{ assignment.assignment_name }}</li>
                            {% endfor %}
                        </ul>
                        {%  else %}
                            <h3 class="card-title pricing-card-title"><small class="text-muted"> No assignments upcoming</small></h3>
                        {%  endif %}

                        <form action="{% url 'assignment_console' course.id %}" method="get">
                            <button type="submit" class="btn btn-lg btn-block btn-primary">Go to Course</button>
                        </form>
                    </div>
                </div>
            {% endfor %}
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Create New Course</h4>
                </div>

                <div class="card-body">
                    <form action="{% url 'course_create' %}" method="post">
                        {% csrf_token %}
                        <input type="text" class="form-control" placeholder="Enter new course name..." value=""
                               name="courseName"/>
                        <br/>
                        <button type="submit" class="btn btn-lg btn-block btn-primary">Create</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

mysite/submitsys/templates/submitsys/student_assignments.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Pricing example for Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/pricing/">

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="pricing.css" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>

<body>

<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">UMBC Submit System</h5>
    <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="#">Courses</a>
        <a class="p-2 text-dark" href="#">Assignments</a>
        <a class="p-2 text-dark" href="#">Support</a>
        <a class="p-2 text-dark" href="#">My Profile</a>
    </nav>
    <a class="btn btn-outline-primary" href="#">Log Out</a>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Assignments for {{course.course_name}}</h1>
    <p class="lead">View all past and upcoming assignments</p>
</div>
<div class="container">
    <div class="card-deck mb-3 text-center">
        {% for assignment in assignments %}
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{assignment.assignment_name}}</h4>
            </div>

            <div class="card-body">
                <h1 class="card-title pricing-card-title"> <small class="text-muted">Previous Submissions:</small></h1>
                <ul class="list-unstyled mt-3 mb-4">
                {% for submission in assignment.submission_set.all %}
                    {% for submissionfile in submission.submissionfile_set.all %}
                        <li>{{submissionfile.file_name}}</li>
                    {% endfor %}
                {% endfor %}
                </ul>

                <form action="{% url 'submission_edit' student.id course.id assignment.id %}" method="get">
                    <button type="submit" class="btn btn-lg btn-block btn-primary">Make New Submission</button>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            <img class="mb-2" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="24"
                 height="24">
            <small class="d-block mb-3 text-muted">© 2017-2018</small>
        </div>
        <div class="col-6 col-md">
            <h5>Resources</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">For Students</a></li>
                <li><a class="text-muted" href="#">For Instructors</a></li>
                <li><a class="text-muted" href="#">For Universities</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Guides</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">FAQ</a></li>
                <li><a class="text-muted" href="#">Quick Start</a></li>
                <li><a class="text-muted" href="#">How-to</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>About</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Team</a></li>
                <li><a class="text-muted" href="#">Contact</a></li>
                <li><a class="text-muted" href="#">Privacy</a></li>
                <li><a class="text-muted" href="#">Terms</a></li>
            </ul>
        </div>
    </div>
</footer>
</div>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="../../assets/js/vendor/popper.min.js"></script>
<script src="../../dist/js/bootstrap.min.js"></script>
<script src="../../assets/js/vendor/holder.min.js"></script>
<script>
    Holder.addTheme('thumb', {
        bg: '#55595c',
        fg: '#eceeef',
        text: 'Thumbnail'
    });
</script>


</body>
</html>

mysite/submitsys/templates/submitsys/student_console.html
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Pricing example for Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/pricing/">

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="pricing.css" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>

<body>

<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">UMBC Submit System</h5>
    <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="#">Courses</a>
        <a class="p-2 text-dark" href="#">Assignments</a>
        <a class="p-2 text-dark" href="#">Support</a>
        <a class="p-2 text-dark" href="#">My Profile</a>
    </nav>
    <a class="btn btn-outline-primary" href="#">Log Out</a>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{student.student_fname}} {{student.student_lname}}'s Courses</h1>
    <p class="lead">Access all of the courses you are enrolled in</p>
</div>
<div class="container">
    <div class="card-deck mb-3 text-center">
        {% for course in courses %}
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{course.course_name}}</h4>
            </div>

            <div class="card-body">
                <h1 class="card-title pricing-card-title"> <small class="text-muted">Upcoming Assignments:</small></h1>
                <ul class="list-unstyled mt-3 mb-4">
                {% for assignment in course.assignment_set.all %}
                    <li>{{assignment.assignment_name}}</li>
                {% endfor %}
                </ul>

                <form action="{% url 'student_assignments' student.id course.id %}" method="get">
                    <button type="submit" class="btn btn-lg btn-block btn-primary">Go to Course</button>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            <img class="mb-2" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="24"
                 height="24">
            <small class="d-block mb-3 text-muted">© 2017-2018</small>
        </div>
        <div class="col-6 col-md">
            <h5>Resources</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">For Students</a></li>
                <li><a class="text-muted" href="#">For Instructors</a></li>
                <li><a class="text-muted" href="#">For Universities</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Guides</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">FAQ</a></li>
                <li><a class="text-muted" href="#">Quick Start</a></li>
                <li><a class="text-muted" href="#">How-to</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>About</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Team</a></li>
                <li><a class="text-muted" href="#">Contact</a></li>
                <li><a class="text-muted" href="#">Privacy</a></li>
                <li><a class="text-muted" href="#">Terms</a></li>
            </ul>
        </div>
    </div>
</footer>
</div>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="../../assets/js/vendor/popper.min.js"></script>
<script src="../../dist/js/bootstrap.min.js"></script>
<script src="../../assets/js/vendor/holder.min.js"></script>
<script>
    Holder.addTheme('thumb', {
        bg: '#55595c',
        fg: '#eceeef',
        text: 'Thumbnail'
    });
</script>


</body>
</html>